allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true

overrides:
  "uuid": "14.0.0"
  "js-cookie": "3.0.8"
  "axios": "1.18.0"

minimumReleaseAgeExclude:
  - "@opendesign-plus/*"
  - "@opendesign-plus-test/*"
  - '@opensig/*'
